{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "execution-aware-scanner.fullname" . }}-datasources
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "execution-aware-scanner.labels" . | nindent 4 }}
    grafana_datasource: "1"
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: {{ .Values.grafana.datasource.url | default "http://prometheus:9090" }}
        isDefault: true
        editable: true
{{- end }}
