[package]
name = "scanner-ebpf"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
# Using exact versions from Cargo.lock to maintain compatibility
aya-ebpf = "=0.1.1"
aya-log-ebpf = "=0.1.1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
