[package]
name = "scanner-ebpf"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
# Pin to 0.1.0 which has the old API compatible with our code
aya-ebpf = "=0.1.0"
aya-log-ebpf = "=0.1.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
