[package]
name = "scanner-ebpf"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
# Pin to older version to avoid API breaking changes in 0.1.x
aya-ebpf = "=0.1.0"
aya-log-ebpf = "=0.1.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
